name = "itsm-frontend"
compatibility_date = "2024-01-01"

pages_build_output_dir = "dist"

[build]
command = "npm run build"

[build.environment_variables]
NODE_VERSION = "18"

# Route configuration
[[pages.routes]]
pattern = "/*"
custom_domain = false

# Asset configuration
[site]
bucket = "./dist"

# Development settings
[dev]
port = 5173
local_protocol = "http"
